# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-gist, jekyll-sitemap]

permalink:        pretty

# Setup
title:            Postmaster
description:      'A light-weight (CodeIgniter, Twitter Bootstrap, SVG) email server (Campaign, Autoresponder and Transactional) and its free (Apache 2.0, AWS: SES, OpsWorks t2.micro, SQS, SNS, S3, RDS t2.micro, Route 53).'
baseurl:          /postmaster

asset_url:        https://rimeofficial.github.io/static

# Custom vars
version:          1.0.0

# Github vars
github:
  username:       rimeofficial

collections:
  docs:
    output:       true
    permalink:    /:path

defaults:
  - scope:
      path:       ''
      type:       docs
    values:
      layout:     page

ga:               UA-41643154-1

app:
  name:           Rime
  domain:         rime.co